const crypto = require('crypto');

/**
 * Password rules that are about WHICH password, not how long (SEC-016, DECISIONS.md D29).
 *
 * This repository is public. Its README, SYSTEM_DOCUMENTATION and CLAUDE.md
 * printed the seeded platform-admin password and the password new accounts got
 * when the admin left the field blank. A password written in a public place is
 * a compromised password (NIST SP 800-63B: check new secrets against values
 * known to be compromised). And a "must change at first sign-in" flag does not
 * help when anyone can do that first sign-in: whoever signs in first chooses the
 * new password and keeps the account.
 *
 * So:
 *  - a published password is refused at sign-in, with the way out (ask the
 *    platform admin, or scripts/password-reset.js on the server for the admin);
 *  - it can never be set again, by anyone, anywhere;
 *  - where no password is given, a random temporary one is generated, shown
 *    once to the admin who asked for it, and must be replaced at first sign-in.
 */

// Every password this repository has ever printed or generated by rule.
const PUBLISHED = new Set(['admin123', 'changeme123']);

// "Teacher@" + four random digits: what a manually added teacher used to get.
// 9,000 possibilities and a public pattern — not published, but guessable.
const GUESSABLE = /^Teacher@\d{4}$/;

// Usernames printed NEXT TO those passwords (the seed, and the docs' credential tables).
// For these the whole sign-in is public; for anyone else an attacker still has to guess
// the username. That difference decides refuse-versus-force-a-change (D29).
const PUBLISHED_USERNAMES = new Set(['admin', 'knjoro', 'famani', 'thassan', 'cmbowe']);

const isPublished = (pw) => PUBLISHED.has(String(pw || ''));
const isPublishedPair = (username, pw) => isPublished(pw) && PUBLISHED_USERNAMES.has(String(username || '').toLowerCase());
const isGuessable = (pw) => GUESSABLE.test(String(pw || ''));

/** Why a new password is not acceptable, or null. Used by every place that sets one. */
function problem(pw) {
  const s = String(pw || '');
  if (s.length < 8) return 'Password must be at least 8 characters.';
  if (isPublished(s)) return 'That password is published and cannot be used. Choose another.';
  if (isGuessable(s)) return 'That password follows a pattern that is easy to guess. Choose another.';
  return null;
}

/**
 * A temporary password an admin can read out or type: 12 characters from an
 * alphabet with no look-alikes (no 0/O, 1/I/L), in three groups — about 59 bits.
 */
function temporary() {
  const A = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
  let out = '';
  // randomInt, not randomBytes % 31: a modulo would favour the first eight letters.
  for (let i = 0; i < 12; i++) out += A[crypto.randomInt(A.length)] + (i === 3 || i === 7 ? '-' : '');
  return out;
}

module.exports = { isPublished, isPublishedPair, isGuessable, problem, temporary, PUBLISHED, PUBLISHED_USERNAMES };
